package agents

const characterSurfaceInspectionPromptV1 = `
表面检查：resource_views.inspectable_surfaces只表示该既有物体允许检查的外表面，不是当前状态。本人可在实际work任务的observation_requests中指定原resource_id、surface=container_exterior或seal_exterior、目的、已知机制和来源；task.resource_ids须含该物体。物体带有可读清单不妨碍检查其已声明外表面，但检查不读取清单或内部内容。只有实际检查后获得的no_visible_damage/visible_damage/indeterminate才是当时本人对指定面的观察；no_visible_damage不等于未曾拆封、密封有效、内容真实、可以开启或整体安全合格。旧观察不会因后来携带、使用或写记录而刷新；书写只能引用本人实际已有的观察来源。`

const worldArbiterSurfaceInspectionPromptV1 = `
表面检查裁决：仅对原work.observation_requests已有且同资源inspectable_surfaces允许的surface，给对应self_executions.observation_results，逐字保留request_id及surface。非空surface结果只用no_visible_damage/visible_damage/indeterminate，并以真实observed_at_day绑定原任务实际工时。必须核对当时本人及目标的实际位置、可达与访问条件、实际照明和有效检查工时，并沿用已验证的开启/破损轨迹；仅工时和枚举合法不证明所见。条件不足只能indeterminate或未执行；无原请求或未执行不能生成观察。检查只涵盖指定既有外表面；不能借表面检查授予数量、文书正文、袋内内容、历史完整性、访问权、开封许可或整体安全结论。物体上的旧清单、T−30等接班旧观察不证明本次外观；不能由任务描述、purpose或新写记录反推或刷新表面事实。空surface仍只用原局部可操作性available/unavailable/inconclusive，不能混用两类结果。`
